[package]
name = "file-writer-app"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { workspace = true }
data = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }
mach-lib = { workspace = true }
