[package]
name = "ingest-indexing"
version = "0.1.0"
edition = "2021"

[dependencies]
data = { workspace = true }
utils = { workspace = true }
clap = { workspace = true }
mach-lib = { workspace = true }
crossbeam = { workspace = true }
